# Generated by Django 2.1 on 2018-09-28 19:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('sov0', models.CharField(max_length=100, verbose_name='sov0 name')),
                ('adm0', models.CharField(max_length=100, verbose_name='adm0 name')),
                ('adm1', models.CharField(blank=True, max_length=100, null=True, verbose_name='adm1 name')),
                ('timezone', models.CharField(blank=True, max_length=30, null=True, verbose_name='timezone')),
                ('worldcity', models.PositiveSmallIntegerField(verbose_name='world city')),
                ('megacity', models.PositiveSmallIntegerField(verbose_name='mega city')),
                ('meganame', models.CharField(blank=True, max_length=50, null=True, verbose_name='mega name')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name': 'city center',
                'verbose_name_plural': 'city centers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FedWireInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.BigIntegerField(unique=True, verbose_name='routing code')),
                ('telex_name', models.CharField(max_length=18, verbose_name='telegraphic name')),
                ('bank_name', models.CharField(max_length=36, verbose_name='bank name')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='state')),
                ('city', models.CharField(max_length=25, verbose_name='city')),
                ('funds_transfer_elegible', models.BooleanField(default=False, verbose_name='funds transfer elegible')),
                ('funds_settlement_only', models.BooleanField(default=False, verbose_name='funds settlement only')),
                ('bes_transfer_elegible', models.BooleanField(default=False, verbose_name='book entry securities transfer elegible')),
                ('modified', models.DateField(blank=True, null=True, verbose_name='last revision')),
            ],
            options={
                'verbose_name': 'FedWire info',
                'verbose_name_plural': 'FedWire infos',
                'ordering': ('bank_code',),
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('post_code', models.CharField(blank=True, max_length=8, null=True)),
                ('metro_code', models.IntegerField(blank=True, null=True)),
                ('area_code', models.CharField(blank=True, max_length=3, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ('city',),
            },
        ),
        migrations.CreateModel(
            name='NetBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.GenericIPAddressField(protocol='IPv4')),
                ('end', models.GenericIPAddressField(protocol='IPv4')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_app.Location')),
            ],
            options={
                'verbose_name': 'IP range',
                'verbose_name_plural': 'IP ranges',
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tzid', models.CharField(max_length=30, verbose_name='time zone ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, help_text='boundary', srid=4326)),
            ],
            options={
                'verbose_name': 'time zone',
                'verbose_name_plural': 'time zones',
                'ordering': ('tzid',),
            },
        ),
    ]
